// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_mitch921.Models;

namespace Mission6_mitch921.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20230214052550_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_mitch921.Models.MovieEntry", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "actionAdventure",
                            Director = "Martin Campbell",
                            Edited = false,
                            Rating = "pg13",
                            Title = "Casino Royale",
                            Year = (short)2006
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "drama",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Rating = "pg13",
                            Title = "The Prestige",
                            Year = (short)2006
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "drama",
                            Director = "James Cameron",
                            Edited = false,
                            Rating = "pg13",
                            Title = "Titanic",
                            Year = (short)1997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
